version: "2"
services:
  # Our node services
  web:
    image: nodemon:6.8.0
    volumes:
     - ./web:/app
    ports:
     - "8080:8080"
    links:
     - redis
     - api

  api:
    build:
      context: ./api
    volumes:
     - ./api:/app
    ports:
     - "8081:80"

  # Some other dependencies
  redis:
    image: redis:3.0
  rabbitmq:
    image: rabbitmq:3.6.5
